export const routePaths = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  medicines: '/medicines',
  inventory: '/inventory',
  sales: '/sales',
  pos: '/pos',
  purchases: '/purchases',
  suppliers: '/suppliers',
  customers: '/customers',
  reports: '/reports',
  employees: '/employees',
  settings: '/settings',
  profile: '/profile',
  notFound: '*',
};